name: Deploy Workers

on:
  push:
    branches:
      - main
    paths:
      - "workers/**"
  workflow_dispatch:

jobs:
  deploy-auth-system:
    runs-on: ubuntu-latest
    name: Deploy Auth System
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Auth Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "workers/auth-system"
          secrets: |
            RESEND_API_KEY
            CLERK_WEBHOOK_SECRET
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          CLERK_WEBHOOK_SECRET: ${{ secrets.CLERK_WEBHOOK_SECRET }}

  deploy-cli-auth:
    runs-on: ubuntu-latest
    name: Deploy CLI Auth
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy CLI Auth Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "workers/cli-auth"
          secrets: |
            JWT_SECRET
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  deploy-install:
    runs-on: ubuntu-latest
    name: Deploy Install Redirect
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Install Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "workers/install"
